### ISSUE TITLE
A non necessary notebook

### ISSUE THREAD

**Issue by Noi-Shitrit** [noi26/InterPython_Workshop_Example#2]
[new_notebook.ipynb](https://github.com/noi26/InterPython_Workshop_Example/blob/main/new_notebook.ipynb) is not necessary.

**Comment by noi26** [comment]
@hombit @rachel3834 @jsobeck  What do you think about deleting this file?

**Comment by jsobeck** [comment]
I agree and would recommend deletion.

**Comment by noi26** [comment]
Thank you for your comment. I deleted the notebook and closing the isseu.
